package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Data;

/**
 * Bairros generated by hbm2java
 */
@Data
@Entity
@Table(name = "BAIRROS", schema = "DBO_CC_PESSOAS")
public class Bairros implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private Long id;
	private String nome;
	private String nomeAbreviado;
	private String usuario;
	private Date dataAlteracao;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DISTRITO", nullable = false)
	private Distritos distritos;

}
