package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BairrosCepsId generated by hbm2java
 */
@Embeddable
public class BairrosCepsId implements java.io.Serializable {

	private Long id;
	private Long cidade;
	private Long distrito;
	private Long bairro;
	private Long logradouro;
	private Long cdCcmLogradouro;
	private Long cdCcmBairro;
	private Long cdCcmCep;
	private String identificacao;
	private String banco;

	public BairrosCepsId() {
	}

	public BairrosCepsId(Long id) {
		this.id = id;
	}

	public BairrosCepsId(Long id, Long cidade, Long distrito, Long bairro, Long logradouro, Long cdCcmLogradouro,
			Long cdCcmBairro, Long cdCcmCep, String identificacao, String banco) {
		this.id = id;
		this.cidade = cidade;
		this.distrito = distrito;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.cdCcmLogradouro = cdCcmLogradouro;
		this.cdCcmBairro = cdCcmBairro;
		this.cdCcmCep = cdCcmCep;
		this.identificacao = identificacao;
		this.banco = banco;
	}

	@Column(name = "ID", nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CIDADE", precision = 10, scale = 0)
	public Long getCidade() {
		return this.cidade;
	}

	public void setCidade(Long cidade) {
		this.cidade = cidade;
	}

	@Column(name = "DISTRITO", precision = 10, scale = 0)
	public Long getDistrito() {
		return this.distrito;
	}

	public void setDistrito(Long distrito) {
		this.distrito = distrito;
	}

	@Column(name = "BAIRRO", precision = 10, scale = 0)
	public Long getBairro() {
		return this.bairro;
	}

	public void setBairro(Long bairro) {
		this.bairro = bairro;
	}

	@Column(name = "LOGRADOURO", precision = 10, scale = 0)
	public Long getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(Long logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "CD_CCM_LOGRADOURO", precision = 10, scale = 0)
	public Long getCdCcmLogradouro() {
		return this.cdCcmLogradouro;
	}

	public void setCdCcmLogradouro(Long cdCcmLogradouro) {
		this.cdCcmLogradouro = cdCcmLogradouro;
	}

	@Column(name = "CD_CCM_BAIRRO", precision = 10, scale = 0)
	public Long getCdCcmBairro() {
		return this.cdCcmBairro;
	}

	public void setCdCcmBairro(Long cdCcmBairro) {
		this.cdCcmBairro = cdCcmBairro;
	}

	@Column(name = "CD_CCM_CEP", precision = 10, scale = 0)
	public Long getCdCcmCep() {
		return this.cdCcmCep;
	}

	public void setCdCcmCep(Long cdCcmCep) {
		this.cdCcmCep = cdCcmCep;
	}

	@Column(name = "IDENTIFICACAO", length = 1)
	public String getIdentificacao() {
		return this.identificacao;
	}

	public void setIdentificacao(String identificacao) {
		this.identificacao = identificacao;
	}

	@Column(name = "BANCO", length = 30)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BairrosCepsId))
			return false;
		BairrosCepsId castOther = (BairrosCepsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getCidade() == castOther.getCidade()) || (this.getCidade() != null
						&& castOther.getCidade() != null && this.getCidade().equals(castOther.getCidade())))
				&& ((this.getDistrito() == castOther.getDistrito()) || (this.getDistrito() != null
						&& castOther.getDistrito() != null && this.getDistrito().equals(castOther.getDistrito())))
				&& ((this.getBairro() == castOther.getBairro()) || (this.getBairro() != null
						&& castOther.getBairro() != null && this.getBairro().equals(castOther.getBairro())))
				&& ((this.getLogradouro() == castOther.getLogradouro()) || (this.getLogradouro() != null
						&& castOther.getLogradouro() != null && this.getLogradouro().equals(castOther.getLogradouro())))
				&& ((this.getCdCcmLogradouro() == castOther.getCdCcmLogradouro())
						|| (this.getCdCcmLogradouro() != null && castOther.getCdCcmLogradouro() != null
								&& this.getCdCcmLogradouro().equals(castOther.getCdCcmLogradouro())))
				&& ((this.getCdCcmBairro() == castOther.getCdCcmBairro())
						|| (this.getCdCcmBairro() != null && castOther.getCdCcmBairro() != null
								&& this.getCdCcmBairro().equals(castOther.getCdCcmBairro())))
				&& ((this.getCdCcmCep() == castOther.getCdCcmCep()) || (this.getCdCcmCep() != null
						&& castOther.getCdCcmCep() != null && this.getCdCcmCep().equals(castOther.getCdCcmCep())))
				&& ((this.getIdentificacao() == castOther.getIdentificacao())
						|| (this.getIdentificacao() != null && castOther.getIdentificacao() != null
								&& this.getIdentificacao().equals(castOther.getIdentificacao())))
				&& ((this.getBanco() == castOther.getBanco()) || (this.getBanco() != null
						&& castOther.getBanco() != null && this.getBanco().equals(castOther.getBanco())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getCidade() == null ? 0 : this.getCidade().hashCode());
		result = 37 * result + (getDistrito() == null ? 0 : this.getDistrito().hashCode());
		result = 37 * result + (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37 * result + (getLogradouro() == null ? 0 : this.getLogradouro().hashCode());
		result = 37 * result + (getCdCcmLogradouro() == null ? 0 : this.getCdCcmLogradouro().hashCode());
		result = 37 * result + (getCdCcmBairro() == null ? 0 : this.getCdCcmBairro().hashCode());
		result = 37 * result + (getCdCcmCep() == null ? 0 : this.getCdCcmCep().hashCode());
		result = 37 * result + (getIdentificacao() == null ? 0 : this.getIdentificacao().hashCode());
		result = 37 * result + (getBanco() == null ? 0 : this.getBanco().hashCode());
		return result;
	}

}
