package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CadUnicoPessoa generated by hbm2java
 */
@Entity
@Table(name = "CAD_UNICO_PESSOA", schema = "DBO_CC_PESSOAS")
public class CadUnicoPessoa implements java.io.Serializable {

	private Long id;
	private Long cdOrigem;
	private Long tipoPessoa;
	private String nome;
	private String fisicaJuridica;
	private Date dataCadastro;
	private Long cpfCnpj;
	private Date dataNascimento;
	private String estadoCivil;
	private String sexo;
	private Long cidadeNascimento;
	private String observacao;
	private String email;
	private String banco;
	private String usuario;
	private Date dataAlteracao;
	private Long pessoasCdUnico;
	private String status;
	private String nomeSomdex;
	private String nomeTransf;

	public CadUnicoPessoa() {
	}

	public CadUnicoPessoa(Long id) {
		this.id = id;
	}

	public CadUnicoPessoa(Long id, Long cdOrigem, Long tipoPessoa, String nome, String fisicaJuridica,
			Date dataCadastro, Long cpfCnpj, Date dataNascimento, String estadoCivil, String sexo,
			Long cidadeNascimento, String observacao, String email, String banco, String usuario, Date dataAlteracao,
			Long pessoasCdUnico, String status, String nomeSomdex, String nomeTransf) {
		this.id = id;
		this.cdOrigem = cdOrigem;
		this.tipoPessoa = tipoPessoa;
		this.nome = nome;
		this.fisicaJuridica = fisicaJuridica;
		this.dataCadastro = dataCadastro;
		this.cpfCnpj = cpfCnpj;
		this.dataNascimento = dataNascimento;
		this.estadoCivil = estadoCivil;
		this.sexo = sexo;
		this.cidadeNascimento = cidadeNascimento;
		this.observacao = observacao;
		this.email = email;
		this.banco = banco;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
		this.pessoasCdUnico = pessoasCdUnico;
		this.status = status;
		this.nomeSomdex = nomeSomdex;
		this.nomeTransf = nomeTransf;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "CD_ORIGEM", precision = 10, scale = 0)
	public Long getCdOrigem() {
		return this.cdOrigem;
	}

	public void setCdOrigem(Long cdOrigem) {
		this.cdOrigem = cdOrigem;
	}

	@Column(name = "TIPO_PESSOA", precision = 5, scale = 0)
	public Long getTipoPessoa() {
		return this.tipoPessoa;
	}

	public void setTipoPessoa(Long tipoPessoa) {
		this.tipoPessoa = tipoPessoa;
	}

	@Column(name = "NOME", length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "FISICA_JURIDICA", length = 1)
	public String getFisicaJuridica() {
		return this.fisicaJuridica;
	}

	public void setFisicaJuridica(String fisicaJuridica) {
		this.fisicaJuridica = fisicaJuridica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CADASTRO", length = 7)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Column(name = "CPF_CNPJ", precision = 14, scale = 0)
	public Long getCpfCnpj() {
		return this.cpfCnpj;
	}

	public void setCpfCnpj(Long cpfCnpj) {
		this.cpfCnpj = cpfCnpj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_NASCIMENTO", length = 7)
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	@Column(name = "ESTADO_CIVIL", length = 1)
	public String getEstadoCivil() {
		return this.estadoCivil;
	}

	public void setEstadoCivil(String estadoCivil) {
		this.estadoCivil = estadoCivil;
	}

	@Column(name = "SEXO", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "CIDADE_NASCIMENTO", precision = 5, scale = 0)
	public Long getCidadeNascimento() {
		return this.cidadeNascimento;
	}

	public void setCidadeNascimento(Long cidadeNascimento) {
		this.cidadeNascimento = cidadeNascimento;
	}

	@Column(name = "OBSERVACAO", length = 1000)
	public String getObservacao() {
		return this.observacao;
	}

	public void setObservacao(String observacao) {
		this.observacao = observacao;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "BANCO", length = 20)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	@Column(name = "USUARIO", length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO", length = 7)
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

	@Column(name = "PESSOAS_CD_UNICO", precision = 10, scale = 0)
	public Long getPessoasCdUnico() {
		return this.pessoasCdUnico;
	}

	public void setPessoasCdUnico(Long pessoasCdUnico) {
		this.pessoasCdUnico = pessoasCdUnico;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "NOME_SOMDEX", length = 100)
	public String getNomeSomdex() {
		return this.nomeSomdex;
	}

	public void setNomeSomdex(String nomeSomdex) {
		this.nomeSomdex = nomeSomdex;
	}

	@Column(name = "NOME_TRANSF", length = 100)
	public String getNomeTransf() {
		return this.nomeTransf;
	}

	public void setNomeTransf(String nomeTransf) {
		this.nomeTransf = nomeTransf;
	}

}
