package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;

import lombok.Data;

/**
 * Ceps generated by hbm2java
 */
@Data
@Entity
@Table(name = "CEPS", schema = "DBO_CC_PESSOAS")
public class Ceps implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private Long id; 
	private Long numero_ini;
	private Long numero_fim;
	private String identificacao;
	
	private String cep;
	private Long logradouro; 
	private Long bairro;
}
