package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * Contatos generated by hbm2java
 */
@Data
@Entity
@Table(name = "CONTATOS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Contatos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(generator = "SEQ_CONTATOS")
	@SequenceGenerator(name = "SEQ_CONTATOS", sequenceName = "SEQ_CONTATOS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private String contato;
	private String usuario;
	private Date dataAlteracao;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_CONTATO", nullable = false)
	private TiposContatos tiposContatos = new TiposContatos();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESSOA", nullable = false)
	private Pessoas pessoas = new Pessoas();


}
