package br.com.codiub.pessoas.entity;
// Generated 20 de mai. de 2021 08:48:57 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DadosPf generated by hbm2java
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "DADOS_PF", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })

//@DiscriminatorValue("dadosPf")
//@PrimaryKeyJoinColumn(name="id")
public class DadosPf {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3547400638231055379L;
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private String cpf;
	private String nomeSocial;
	private Long raca;
	private Long etnia;
	private Long cor;
	private Long estadoCivil;
	private String recebeBf;
	private Long cartaoSus;
	private String sexo;
	private Long localNascimento;
	private String mae;
	private String pai;
	
	
}
