package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DadosPj generated by hbm2java
 */


@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "DADOS_PJ", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })

//@DiscriminatorValue("dadosPj")
//@PrimaryKeyJoinColumn(name="id")
public class DadosPj {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1472198430400403711L;
	
	@Id
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private String cnpj;
	private String nomeFantasia;
	private String objetoSocial;
	private String microEmpresa;
	private String conjuge;
	private Long tipoEmpresa;
	
}
