package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DadosCompPessoasEscola generated by hbm2java
 */
@Entity
@Table(name = "DADOS_COMP_PESSOAS_ESCOLA", schema = "DBO_CC_PESSOAS")
public class DadosCompPessoasEscola implements java.io.Serializable {

	private Long id;
	private Long pessoa;
	private Long scolaOutraesp;
	private Long ransEscpub;
	private Long espTranesc;
	private String alunoInep;
	private String ufNascimento;
	private Long escolaOutraesp;
	private Long transEscpub;
	private Long respTranesc;
	private Long auxLedor;
	private Long auxTransc;
	private Long guiaInterp;
	private Long interpLibras;
	private Long leituraLabial;
	private Long provaAmplFonte16;
	private Long provaAmplFonte20;
	private Long provaAmplFonte24;
	private Long provaBraile;
	private Long nenhumAux;
	private Long rodVansKombis;
	private Long rodMicroonibus;
	private Long rodOnibus;
	private Long rodBicicleta;
	private Long rodTracaoAnimal;
	private Long rodOutros;
	private Long aquaEmb5alu;
	private Long aquaEmb5a15alu;
	private Long aquaEmb15a35alu;
	private Long aquaEmbAcima35alu;
	private Long ferroTremMetro;
	private String usuario;
	private Date dataAlteracao;

	public DadosCompPessoasEscola() {
	}

	public DadosCompPessoasEscola(Long id, Long pessoa) {
		this.id = id;
		this.pessoa = pessoa;
	}

	public DadosCompPessoasEscola(Long id, Long pessoa, Long scolaOutraesp, Long ransEscpub, Long espTranesc,
			String alunoInep, String ufNascimento, Long escolaOutraesp, Long transEscpub, Long respTranesc,
			Long auxLedor, Long auxTransc, Long guiaInterp, Long interpLibras, Long leituraLabial,
			Long provaAmplFonte16, Long provaAmplFonte20, Long provaAmplFonte24, Long provaBraile, Long nenhumAux,
			Long rodVansKombis, Long rodMicroonibus, Long rodOnibus, Long rodBicicleta, Long rodTracaoAnimal,
			Long rodOutros, Long aquaEmb5alu, Long aquaEmb5a15alu, Long aquaEmb15a35alu, Long aquaEmbAcima35alu,
			Long ferroTremMetro, String usuario, Date dataAlteracao) {
		this.id = id;
		this.pessoa = pessoa;
		this.scolaOutraesp = scolaOutraesp;
		this.ransEscpub = ransEscpub;
		this.espTranesc = espTranesc;
		this.alunoInep = alunoInep;
		this.ufNascimento = ufNascimento;
		this.escolaOutraesp = escolaOutraesp;
		this.transEscpub = transEscpub;
		this.respTranesc = respTranesc;
		this.auxLedor = auxLedor;
		this.auxTransc = auxTransc;
		this.guiaInterp = guiaInterp;
		this.interpLibras = interpLibras;
		this.leituraLabial = leituraLabial;
		this.provaAmplFonte16 = provaAmplFonte16;
		this.provaAmplFonte20 = provaAmplFonte20;
		this.provaAmplFonte24 = provaAmplFonte24;
		this.provaBraile = provaBraile;
		this.nenhumAux = nenhumAux;
		this.rodVansKombis = rodVansKombis;
		this.rodMicroonibus = rodMicroonibus;
		this.rodOnibus = rodOnibus;
		this.rodBicicleta = rodBicicleta;
		this.rodTracaoAnimal = rodTracaoAnimal;
		this.rodOutros = rodOutros;
		this.aquaEmb5alu = aquaEmb5alu;
		this.aquaEmb5a15alu = aquaEmb5a15alu;
		this.aquaEmb15a35alu = aquaEmb15a35alu;
		this.aquaEmbAcima35alu = aquaEmbAcima35alu;
		this.ferroTremMetro = ferroTremMetro;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PESSOA", nullable = false, precision = 10, scale = 0)
	public Long getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Long pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "SCOLA_OUTRAESP", precision = 5, scale = 0)
	public Long getScolaOutraesp() {
		return this.scolaOutraesp;
	}

	public void setScolaOutraesp(Long scolaOutraesp) {
		this.scolaOutraesp = scolaOutraesp;
	}

	@Column(name = "RANS_ESCPUB", precision = 5, scale = 0)
	public Long getRansEscpub() {
		return this.ransEscpub;
	}

	public void setRansEscpub(Long ransEscpub) {
		this.ransEscpub = ransEscpub;
	}

	@Column(name = "ESP_TRANESC", precision = 5, scale = 0)
	public Long getEspTranesc() {
		return this.espTranesc;
	}

	public void setEspTranesc(Long espTranesc) {
		this.espTranesc = espTranesc;
	}

	@Column(name = "ALUNO_INEP", length = 12)
	public String getAlunoInep() {
		return this.alunoInep;
	}

	public void setAlunoInep(String alunoInep) {
		this.alunoInep = alunoInep;
	}

	@Column(name = "UF_NASCIMENTO", length = 2)
	public String getUfNascimento() {
		return this.ufNascimento;
	}

	public void setUfNascimento(String ufNascimento) {
		this.ufNascimento = ufNascimento;
	}

	@Column(name = "ESCOLA_OUTRAESP", precision = 5, scale = 0)
	public Long getEscolaOutraesp() {
		return this.escolaOutraesp;
	}

	public void setEscolaOutraesp(Long escolaOutraesp) {
		this.escolaOutraesp = escolaOutraesp;
	}

	@Column(name = "TRANS_ESCPUB", precision = 5, scale = 0)
	public Long getTransEscpub() {
		return this.transEscpub;
	}

	public void setTransEscpub(Long transEscpub) {
		this.transEscpub = transEscpub;
	}

	@Column(name = "RESP_TRANESC", precision = 5, scale = 0)
	public Long getRespTranesc() {
		return this.respTranesc;
	}

	public void setRespTranesc(Long respTranesc) {
		this.respTranesc = respTranesc;
	}

	@Column(name = "AUX_LEDOR", precision = 5, scale = 0)
	public Long getAuxLedor() {
		return this.auxLedor;
	}

	public void setAuxLedor(Long auxLedor) {
		this.auxLedor = auxLedor;
	}

	@Column(name = "AUX_TRANSC", precision = 5, scale = 0)
	public Long getAuxTransc() {
		return this.auxTransc;
	}

	public void setAuxTransc(Long auxTransc) {
		this.auxTransc = auxTransc;
	}

	@Column(name = "GUIA_INTERP", precision = 5, scale = 0)
	public Long getGuiaInterp() {
		return this.guiaInterp;
	}

	public void setGuiaInterp(Long guiaInterp) {
		this.guiaInterp = guiaInterp;
	}

	@Column(name = "INTERP_LIBRAS", precision = 5, scale = 0)
	public Long getInterpLibras() {
		return this.interpLibras;
	}

	public void setInterpLibras(Long interpLibras) {
		this.interpLibras = interpLibras;
	}

	@Column(name = "LEITURA_LABIAL", precision = 5, scale = 0)
	public Long getLeituraLabial() {
		return this.leituraLabial;
	}

	public void setLeituraLabial(Long leituraLabial) {
		this.leituraLabial = leituraLabial;
	}

	@Column(name = "PROVA_AMPL_FONTE16", precision = 5, scale = 0)
	public Long getProvaAmplFonte16() {
		return this.provaAmplFonte16;
	}

	public void setProvaAmplFonte16(Long provaAmplFonte16) {
		this.provaAmplFonte16 = provaAmplFonte16;
	}

	@Column(name = "PROVA_AMPL_FONTE20", precision = 5, scale = 0)
	public Long getProvaAmplFonte20() {
		return this.provaAmplFonte20;
	}

	public void setProvaAmplFonte20(Long provaAmplFonte20) {
		this.provaAmplFonte20 = provaAmplFonte20;
	}

	@Column(name = "PROVA_AMPL_FONTE24", precision = 5, scale = 0)
	public Long getProvaAmplFonte24() {
		return this.provaAmplFonte24;
	}

	public void setProvaAmplFonte24(Long provaAmplFonte24) {
		this.provaAmplFonte24 = provaAmplFonte24;
	}

	@Column(name = "PROVA_BRAILE", precision = 5, scale = 0)
	public Long getProvaBraile() {
		return this.provaBraile;
	}

	public void setProvaBraile(Long provaBraile) {
		this.provaBraile = provaBraile;
	}

	@Column(name = "NENHUM_AUX", precision = 5, scale = 0)
	public Long getNenhumAux() {
		return this.nenhumAux;
	}

	public void setNenhumAux(Long nenhumAux) {
		this.nenhumAux = nenhumAux;
	}

	@Column(name = "ROD_VANS_KOMBIS", precision = 5, scale = 0)
	public Long getRodVansKombis() {
		return this.rodVansKombis;
	}

	public void setRodVansKombis(Long rodVansKombis) {
		this.rodVansKombis = rodVansKombis;
	}

	@Column(name = "ROD_MICROONIBUS", precision = 5, scale = 0)
	public Long getRodMicroonibus() {
		return this.rodMicroonibus;
	}

	public void setRodMicroonibus(Long rodMicroonibus) {
		this.rodMicroonibus = rodMicroonibus;
	}

	@Column(name = "ROD_ONIBUS", precision = 5, scale = 0)
	public Long getRodOnibus() {
		return this.rodOnibus;
	}

	public void setRodOnibus(Long rodOnibus) {
		this.rodOnibus = rodOnibus;
	}

	@Column(name = "ROD_BICICLETA", precision = 5, scale = 0)
	public Long getRodBicicleta() {
		return this.rodBicicleta;
	}

	public void setRodBicicleta(Long rodBicicleta) {
		this.rodBicicleta = rodBicicleta;
	}

	@Column(name = "ROD_TRACAO_ANIMAL", precision = 5, scale = 0)
	public Long getRodTracaoAnimal() {
		return this.rodTracaoAnimal;
	}

	public void setRodTracaoAnimal(Long rodTracaoAnimal) {
		this.rodTracaoAnimal = rodTracaoAnimal;
	}

	@Column(name = "ROD_OUTROS", precision = 5, scale = 0)
	public Long getRodOutros() {
		return this.rodOutros;
	}

	public void setRodOutros(Long rodOutros) {
		this.rodOutros = rodOutros;
	}

	@Column(name = "AQUA_EMB_5ALU", precision = 5, scale = 0)
	public Long getAquaEmb5alu() {
		return this.aquaEmb5alu;
	}

	public void setAquaEmb5alu(Long aquaEmb5alu) {
		this.aquaEmb5alu = aquaEmb5alu;
	}

	@Column(name = "AQUA_EMB_5A15ALU", precision = 5, scale = 0)
	public Long getAquaEmb5a15alu() {
		return this.aquaEmb5a15alu;
	}

	public void setAquaEmb5a15alu(Long aquaEmb5a15alu) {
		this.aquaEmb5a15alu = aquaEmb5a15alu;
	}

	@Column(name = "AQUA_EMB_15A35ALU", precision = 5, scale = 0)
	public Long getAquaEmb15a35alu() {
		return this.aquaEmb15a35alu;
	}

	public void setAquaEmb15a35alu(Long aquaEmb15a35alu) {
		this.aquaEmb15a35alu = aquaEmb15a35alu;
	}

	@Column(name = "AQUA_EMB_ACIMA35ALU", precision = 5, scale = 0)
	public Long getAquaEmbAcima35alu() {
		return this.aquaEmbAcima35alu;
	}

	public void setAquaEmbAcima35alu(Long aquaEmbAcima35alu) {
		this.aquaEmbAcima35alu = aquaEmbAcima35alu;
	}

	@Column(name = "FERRO_TREM_METRO", precision = 5, scale = 0)
	public Long getFerroTremMetro() {
		return this.ferroTremMetro;
	}

	public void setFerroTremMetro(Long ferroTremMetro) {
		this.ferroTremMetro = ferroTremMetro;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
