package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DadosCompPessoasSaneamento generated by hbm2java
 */
@Entity
@Table(name = "DADOS_COMP_PESSOAS_SANEAMENTO", schema = "DBO_CC_PESSOAS")
public class DadosCompPessoasSaneamento implements java.io.Serializable {

	private Long id;
	private Long pessoa;
	private String aposentado;
	private Date dataInicioBeneficio;
	private Date dataFimBeneficio;
	private Long rendaMensal;
	private String usuario;
	private Date dataAlteracao;

	public DadosCompPessoasSaneamento() {
	}

	public DadosCompPessoasSaneamento(Long id, Long pessoa) {
		this.id = id;
		this.pessoa = pessoa;
	}

	public DadosCompPessoasSaneamento(Long id, Long pessoa, String aposentado, Date dataInicioBeneficio,
			Date dataFimBeneficio, Long rendaMensal, String usuario, Date dataAlteracao) {
		this.id = id;
		this.pessoa = pessoa;
		this.aposentado = aposentado;
		this.dataInicioBeneficio = dataInicioBeneficio;
		this.dataFimBeneficio = dataFimBeneficio;
		this.rendaMensal = rendaMensal;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PESSOA", nullable = false, precision = 10, scale = 0)
	public Long getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Long pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "APOSENTADO", length = 2)
	public String getAposentado() {
		return this.aposentado;
	}

	public void setAposentado(String aposentado) {
		this.aposentado = aposentado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_INICIO_BENEFICIO", length = 7)
	public Date getDataInicioBeneficio() {
		return this.dataInicioBeneficio;
	}

	public void setDataInicioBeneficio(Date dataInicioBeneficio) {
		this.dataInicioBeneficio = dataInicioBeneficio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_FIM_BENEFICIO", length = 7)
	public Date getDataFimBeneficio() {
		return this.dataFimBeneficio;
	}

	public void setDataFimBeneficio(Date dataFimBeneficio) {
		this.dataFimBeneficio = dataFimBeneficio;
	}

	@Column(name = "RENDA_MENSAL", precision = 10)
	public Long getRendaMensal() {
		return this.rendaMensal;
	}

	public void setRendaMensal(Long rendaMensal) {
		this.rendaMensal = rendaMensal;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
