package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * Documentos generated by hbm2java
 */
@Data
@Entity
@Table(name = "DOCUMENTOS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Documentos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(generator = "SEQ_DOCUMENTOS")
	@SequenceGenerator(name = "SEQ_DOCUMENTOS", sequenceName = "SEQ_DOCUMENTOS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private String numeroDocumento;
	private Date dataDocumento;
	private Date dataExpedicao;
	private String documentoOrigem;
	private String orgaoExpedidor;
	private String numeroRegistroCnh;
	private Date dataPrimeiraCnh;
	private Date dataValidadeCnh;
	private String categoriaCnh;
	private Long tituloEleitoral;
	private Long zona;
	private Long secao;
	private String termo;
	private String folha;
	private String livro;
	private Date dtEmisCert;
	private Long ufCartorio;
	private Long cidadeCartorio;
	private Long cartorio;
	private String usuario;
	private Date dataAlteracao;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_DOCUMENTO", nullable = false)
	private TiposDocumentos tiposDocumentos = new TiposDocumentos();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESSOA", nullable = false)
	private Pessoas pessoas = new Pessoas();
	
}
