package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * EmpresasPessoas generated by hbm2java
 */
@Data
@Entity
@Table(name = "EMPRESAS_PESSOAS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class EmpresasPessoas implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(generator = "SEQ_EMPRESAS_PESSOAS")
	@SequenceGenerator(name = "SEQ_EMPRESAS_PESSOAS", sequenceName = "SEQ_EMPRESAS_PESSOAS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private Long participacao;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_EMPRESA")
	private Pessoas pessoasEmpresas = new Pessoas();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PESSOA")
	private Pessoas pessoasPessoas = new Pessoas();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VINCULO")
	private TiposVinculosEmpresas tiposVinculosEmpresas;
	
}
