package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * Enderecos generated by hbm2java
 */
@Data
@Entity
@Table(name = "ENDERECOS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Enderecos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(generator = "SEQ_ENDERECOS")
	@SequenceGenerator(name = "SEQ_ENDERECOS", sequenceName = "SEQ_ENDERECOS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false)
	private Long id;
	private Long numero;
	private String complemento;
	private String usuario;
	private Date dataAlteracao;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TP_ENDERECO", nullable = false)
	private TiposEnderecos tiposEnderecos = new TiposEnderecos();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PESSOA", nullable = false)
	private Pessoas pessoas = new Pessoas();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BAIRRO", nullable = false)
	private Bairros bairros = new Bairros();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LOGRADOURO", nullable = false)
	private Logradouros logradouros = new Logradouros();
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CEP", nullable = false)
	private Ceps ceps = new Ceps();
	
}
