package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * Etnias generated by hbm2java
 */
@Data
@Entity
@Table(name = "ETNIAS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Etnias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1671418914475678882L;
	private Long id;
	private String descricao;
	private String codCadsus;

	@Id
	@GeneratedValue(generator = "SEQ_ETNIAS")
	@SequenceGenerator(name = "SEQ_ETNIAS", sequenceName = "SEQ_ETNIAS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}
	
}
