package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Indices generated by hbm2java
 */
@Entity
@Table(name = "INDICES", schema = "DBO_CC_PESSOAS")
public class Indices implements java.io.Serializable {

	private Long id;
	private Long indice;
	private String nome;
	private String sigla;
	private String fonteDados;
	private String tipoIndice;
	private String usuario;
	private Date dataAlteracao;

	public Indices() {
	}

	public Indices(Long id, Long indice) {
		this.id = id;
		this.indice = indice;
	}

	public Indices(Long id, Long indice, String nome, String sigla, String fonteDados, String tipoIndice,
			String usuario, Date dataAlteracao) {
		this.id = id;
		this.indice = indice;
		this.nome = nome;
		this.sigla = sigla;
		this.fonteDados = fonteDados;
		this.tipoIndice = tipoIndice;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "INDICE", nullable = false, precision = 10, scale = 0)
	public Long getIndice() {
		return this.indice;
	}

	public void setIndice(Long indice) {
		this.indice = indice;
	}

	@Column(name = "NOME")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "SIGLA", length = 5)
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "FONTE_DADOS", length = 100)
	public String getFonteDados() {
		return this.fonteDados;
	}

	public void setFonteDados(String fonteDados) {
		this.fonteDados = fonteDados;
	}

	@Column(name = "TIPO_INDICE", length = 1)
	public String getTipoIndice() {
		return this.tipoIndice;
	}

	public void setTipoIndice(String tipoIndice) {
		this.tipoIndice = tipoIndice;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
