package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PessoasProfissoes generated by hbm2java
 */
@Entity
@Table(name = "PESSOAS_PROFISSOES", schema = "DBO_CC_PESSOAS")
public class PessoasProfissoes implements java.io.Serializable {

	private Long id;
	private Long pessoa;
	private Long profissao;
	private String usuario;
	private Date dataAlteracao;

	public PessoasProfissoes() {
	}

	public PessoasProfissoes(Long id, Long pessoa, Long profissao) {
		this.id = id;
		this.pessoa = pessoa;
		this.profissao = profissao;
	}

	public PessoasProfissoes(Long id, Long pessoa, Long profissao, String usuario, Date dataAlteracao) {
		this.id = id;
		this.pessoa = pessoa;
		this.profissao = profissao;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "PESSOA", nullable = false, precision = 10, scale = 0)
	public Long getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Long pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "PROFISSAO", nullable = false, precision = 10, scale = 0)
	public Long getProfissao() {
		return this.profissao;
	}

	public void setProfissao(Long profissao) {
		this.profissao = profissao;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
