package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Relacionamentos generated by hbm2java
 */
@Entity
@Table(name = "RELACIONAMENTOS", schema = "DBO_CC_PESSOAS")
public class Relacionamentos implements java.io.Serializable {

	private Long id;
	private Long tipoRelacionamento;
	private Long pessoa1;
	private Long pessoa2;
	private Long cpf;
	private String usuario;
	private Date dataAlteracao;

	public Relacionamentos() {
	}

	public Relacionamentos(Long id, Long tipoRelacionamento, Long pessoa1) {
		this.id = id;
		this.tipoRelacionamento = tipoRelacionamento;
		this.pessoa1 = pessoa1;
	}

	public Relacionamentos(Long id, Long tipoRelacionamento, Long pessoa1, Long pessoa2, Long cpf, String usuario,
			Date dataAlteracao) {
		this.id = id;
		this.tipoRelacionamento = tipoRelacionamento;
		this.pessoa1 = pessoa1;
		this.pessoa2 = pessoa2;
		this.cpf = cpf;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TIPO_RELACIONAMENTO", nullable = false, precision = 10, scale = 0)
	public Long getTipoRelacionamento() {
		return this.tipoRelacionamento;
	}

	public void setTipoRelacionamento(Long tipoRelacionamento) {
		this.tipoRelacionamento = tipoRelacionamento;
	}

	@Column(name = "PESSOA_1", nullable = false, precision = 10, scale = 0)
	public Long getPessoa1() {
		return this.pessoa1;
	}

	public void setPessoa1(Long pessoa1) {
		this.pessoa1 = pessoa1;
	}

	@Column(name = "PESSOA_2", precision = 10, scale = 0)
	public Long getPessoa2() {
		return this.pessoa2;
	}

	public void setPessoa2(Long pessoa2) {
		this.pessoa2 = pessoa2;
	}

	@Column(name = "CPF", precision = 11, scale = 0)
	public Long getCpf() {
		return this.cpf;
	}

	public void setCpf(Long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
