package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SociosId generated by hbm2java
 */
@Embeddable
public class SociosId implements java.io.Serializable {

	private Long estabelecimento;
	private Long pessoa;
	private Long participacao;
	private Long usuario;

	public SociosId() {
	}

	public SociosId(Long estabelecimento, Long pessoa, Long participacao, Long usuario) {
		this.estabelecimento = estabelecimento;
		this.pessoa = pessoa;
		this.participacao = participacao;
		this.usuario = usuario;
	}

	@Column(name = "ESTABELECIMENTO", precision = 15, scale = 0)
	public Long getEstabelecimento() {
		return this.estabelecimento;
	}

	public void setEstabelecimento(Long estabelecimento) {
		this.estabelecimento = estabelecimento;
	}

	@Column(name = "PESSOA", precision = 15, scale = 0)
	public Long getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Long pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "PARTICIPACAO", precision = 9, scale = 6)
	public Long getParticipacao() {
		return this.participacao;
	}

	public void setParticipacao(Long participacao) {
		this.participacao = participacao;
	}

	@Column(name = "USUARIO", precision = 15, scale = 0)
	public Long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Long usuario) {
		this.usuario = usuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SociosId))
			return false;
		SociosId castOther = (SociosId) other;

		return ((this.getEstabelecimento() == castOther.getEstabelecimento())
				|| (this.getEstabelecimento() != null && castOther.getEstabelecimento() != null
						&& this.getEstabelecimento().equals(castOther.getEstabelecimento())))
				&& ((this.getPessoa() == castOther.getPessoa()) || (this.getPessoa() != null
						&& castOther.getPessoa() != null && this.getPessoa().equals(castOther.getPessoa())))
				&& ((this.getParticipacao() == castOther.getParticipacao())
						|| (this.getParticipacao() != null && castOther.getParticipacao() != null
								&& this.getParticipacao().equals(castOther.getParticipacao())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEstabelecimento() == null ? 0 : this.getEstabelecimento().hashCode());
		result = 37 * result + (getPessoa() == null ? 0 : this.getPessoa().hashCode());
		result = 37 * result + (getParticipacao() == null ? 0 : this.getParticipacao().hashCode());
		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		return result;
	}

}
