package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Socios generated by hbm2java
 */
@Entity
@Table(name = "SOCIOS", schema = "DBO_CC_PESSOAS")
public class Socios implements java.io.Serializable {

	private SociosId id;

	public Socios() {
	}

	public Socios(SociosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "estabelecimento", column = @Column(name = "ESTABELECIMENTO", precision = 15, scale = 0)),
			@AttributeOverride(name = "pessoa", column = @Column(name = "PESSOA", precision = 15, scale = 0)),
			@AttributeOverride(name = "participacao", column = @Column(name = "PARTICIPACAO", precision = 9, scale = 6)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", precision = 15, scale = 0)) })
	public SociosId getId() {
		return this.id;
	}

	public void setId(SociosId id) {
		this.id = id;
	}

}
