package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.Data;

/**
 * TiposEstadosCivis generated by hbm2java
 */
@Data
@Entity
@Table(name = "TIPOS_ESTADOS_CIVIS", schema = "DBO_CC_PESSOAS")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class TiposEstadosCivis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6812814054659671415L;
	private Long id;
	private String sigla;
	private String descricao;

	@Id
	@GeneratedValue(generator = "SEQ_TIPOS_ESTADOS_CIVIS")
	@SequenceGenerator(name = "SEQ_TIPOS_ESTADOS_CIVIS", sequenceName = "SEQ_TIPOS_ESTADOS_CIVIS", allocationSize = 1)
	@Column(name = "ID", unique = true, nullable = false, precision = 3, scale = 0)
	public Long getId() {
		return this.id;
	}
	
}
