package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TiposEmpresasId generated by hbm2java
 */
@Embeddable
public class TiposEmpresasId implements java.io.Serializable {

	private Long tipoEstabelecimento;
	private String descricao;
	private Long usuario;

	public TiposEmpresasId() {
	}

	public TiposEmpresasId(Long tipoEstabelecimento, String descricao, Long usuario) {
		this.tipoEstabelecimento = tipoEstabelecimento;
		this.descricao = descricao;
		this.usuario = usuario;
	}

	@Column(name = "TIPO_ESTABELECIMENTO", precision = 5, scale = 0)
	public Long getTipoEstabelecimento() {
		return this.tipoEstabelecimento;
	}

	public void setTipoEstabelecimento(Long tipoEstabelecimento) {
		this.tipoEstabelecimento = tipoEstabelecimento;
	}

	@Column(name = "DESCRICAO", length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "USUARIO", precision = 15, scale = 0)
	public Long getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Long usuario) {
		this.usuario = usuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiposEmpresasId))
			return false;
		TiposEmpresasId castOther = (TiposEmpresasId) other;

		return ((this.getTipoEstabelecimento() == castOther.getTipoEstabelecimento())
				|| (this.getTipoEstabelecimento() != null && castOther.getTipoEstabelecimento() != null
						&& this.getTipoEstabelecimento().equals(castOther.getTipoEstabelecimento())))
				&& ((this.getDescricao() == castOther.getDescricao()) || (this.getDescricao() != null
						&& castOther.getDescricao() != null && this.getDescricao().equals(castOther.getDescricao())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario().equals(castOther.getUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTipoEstabelecimento() == null ? 0 : this.getTipoEstabelecimento().hashCode());
		result = 37 * result + (getDescricao() == null ? 0 : this.getDescricao().hashCode());
		result = 37 * result + (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		return result;
	}

}
