package br.com.codiub.pessoas.entity;
// Generated 3 de mai. de 2021 14:41:28 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ValoresIndices generated by hbm2java
 */
@Entity
@Table(name = "VALORES_INDICES", schema = "DBO_CC_PESSOAS")
public class ValoresIndices implements java.io.Serializable {

	private Long id;
	private Long indice;
	private Date dataInicial;
	private Date dataFinal;
	private Long valor;
	private String sinal;
	private String usuario;
	private Date dataAlteracao;

	public ValoresIndices() {
	}

	public ValoresIndices(Long id) {
		this.id = id;
	}

	public ValoresIndices(Long id, Long indice, Date dataInicial, Date dataFinal, Long valor, String sinal,
			String usuario, Date dataAlteracao) {
		this.id = id;
		this.indice = indice;
		this.dataInicial = dataInicial;
		this.dataFinal = dataFinal;
		this.valor = valor;
		this.sinal = sinal;
		this.usuario = usuario;
		this.dataAlteracao = dataAlteracao;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "INDICE", precision = 10, scale = 0)
	public Long getIndice() {
		return this.indice;
	}

	public void setIndice(Long indice) {
		this.indice = indice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_INICIAL", length = 7)
	public Date getDataInicial() {
		return this.dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_FINAL", length = 7)
	public Date getDataFinal() {
		return this.dataFinal;
	}

	public void setDataFinal(Date dataFinal) {
		this.dataFinal = dataFinal;
	}

	@Column(name = "VALOR", precision = 18, scale = 6)
	public Long getValor() {
		return this.valor;
	}

	public void setValor(Long valor) {
		this.valor = valor;
	}

	@Column(name = "SINAL", length = 1)
	public String getSinal() {
		return this.sinal;
	}

	public void setSinal(String sinal) {
		this.sinal = sinal;
	}

	@Column(name = "USUARIO", length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ALTERACAO")
	public Date getDataAlteracao() {
		return this.dataAlteracao;
	}

	public void setDataAlteracao(Date dataAlteracao) {
		this.dataAlteracao = dataAlteracao;
	}

}
